version: '2.1'
services:

  unbound:
    image: mailcow/unbound-mailcow:1.0
    build: ${DATA_DIR}/Dockerfiles/unbound
    command: /usr/sbin/unbound
    volumes:
      - ${DATA_DIR}/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
    restart: always
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.254
    #     aliases:
    #       - unbound

  mysql:
    image: mariadb:10.2
    command: mysqld --max_allowed_packet=192M --max-connections=1500 --innodb-strict-mode=0 --skip-host-cache --skip-name-resolve --log-warnings=0
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - ${DATA_DIR}/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.250
    #     aliases:
    #       - mysql

  redis:
    image: redis:alpine
    volumes:
      - redis-vol-1:/data/
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.249
    #     aliases:
    #       - redis

  clamd:
    image: mailcow/clamd:1.5
    build: ${DATA_DIR}/Dockerfiles/clamd
    environment:
      - SKIP_CLAMD=${SKIP_CLAMD}
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - clamd

  rspamd:
    image: mailcow/rspamd:1.14
    build: ${DATA_DIR}/Dockerfiles/rspamd
    stop_grace_period: 30s
    depends_on:
      - nginx
    volumes:
      - ${DATA_DIR}/conf/rspamd/custom/:/etc/rspamd/custom:ro
      - ${DATA_DIR}/conf/rspamd/override.d/:/etc/rspamd/override.d:ro
      - ${DATA_DIR}/conf/rspamd/local.d/:/etc/rspamd/local.d:ro
      - ${DATA_DIR}/conf/rspamd/lua/:/etc/rspamd/lua/:ro
      - dkim-vol-1:/data/dkim
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    # hostname: rspamd
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.253
    #     aliases:
    #       - rspamd

  php-fpm:
    image: mailcow/phpfpm:1.5
    build: ${DATA_DIR}/Dockerfiles/phpfpm
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis
    volumes:
      - ${DATA_DIR}/web:/web:rw
      - ${DATA_DIR}/conf/rspamd/dynmaps:/dynmaps:ro
      - dkim-vol-1:/data/dkim
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - phpfpm

  sogo:
    image: mailcow/sogo:1.10
    build: ${DATA_DIR}/Dockerfiles/sogo
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    volumes:
      - ${DATA_DIR}/conf/sogo/:/etc/sogo/
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.252
    #     aliases:
    #       - sogo

  dovecot:
    image: mailcow/dovecot:1.12
    build: ${DATA_DIR}/Dockerfiles/dovecot
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ${DATA_DIR}/conf/dovecot:/usr/local/etc/dovecot
      - ${DATA_DIR}/assets/ssl:/etc/ssl/mail/:ro
      - ${DATA_DIR}/conf/sogo/:/etc/sogo/
      - vmail-vol-1:/var/vmail
      - crypt-vol-1:/mail_crypt/
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    ports:
      - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - dovecot

  postfix:
    image: mailcow/postfix:1.7
    build: ${DATA_DIR}/Dockerfiles/postfix
    volumes:
      - ${DATA_DIR}/conf/postfix:/opt/postfix/conf
      - ${DATA_DIR}/assets/ssl:/etc/ssl/mail/:ro
      - postfix-vol-1:/var/spool/postfix
      - crypt-vol-1:/var/lib/zeyple
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    restart: always
    hostname: ${MAILCOW_HOSTNAME}
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - postfix

  memcached:
    image: memcached:alpine
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - memcached

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - sogo
      - php-fpm
      - redis
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
        envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
        envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
        nginx -qt &&
        until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
        until ping sogo -c1 > /dev/null; do sleep 1; done &&
        until ping redis -c1 > /dev/null; do sleep 1; done &&
        exec nginx -g 'daemon off;'"
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTP_PORT=${HTTP_PORT:-80}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
    volumes:
      - ${DATA_DIR}/web:/web:ro
      - ${DATA_DIR}/conf/rspamd/dynmaps:/dynmaps:ro
      - ${DATA_DIR}/assets/ssl/:/etc/ssl/mail/:ro
      - ${DATA_DIR}/conf/nginx/:/etc/nginx/conf.d/:rw
    ports:
      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:443"
      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:80"
    restart: always
    labels:
      rap.host: ${MAILCOW_HOSTNAME}
      rap.port: ${HTTP_PORT:-80}
      rap.http_listen_ports: ${HTTP_PORT:-80}
      rap.https_listen_ports: ${HTTPS_PORT:-443}
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.251
    #     aliases:
    #       - nginx

  acme:
    depends_on:
      - nginx
      - mysql
    image: mailcow/acme:1.24
    build: ${DATA_DIR}/Dockerfiles/acme
    environment:
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
    volumes:
      - ${DATA_DIR}/web/.well-known/acme-challenge:/var/www/acme:rw
      - ${DATA_DIR}/assets/ssl:/var/lib/acme/:rw
      - ${DATA_DIR}/assets/ssl-example:/var/lib/ssl-example/:ro
    restart: always
    # dns:
    #   - 172.22.1.254
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - acme

  fail2ban:
    image: mailcow/fail2ban:1.9
    build: ${DATA_DIR}/Dockerfiles/fail2ban
    stop_grace_period: 30s
    depends_on:
      - dovecot
      - postfix
      - sogo
      - php-fpm
      - redis
    restart: always
    privileged: true
    environment:
      - TZ=${TZ}
      - SKIP_FAIL2BAN=${SKIP_FAIL2BAN:-n}
    volumes:
      - /lib/modules:/lib/modules:ro
    # network_mode: "host"
    # dns:
      # - 172.22.1.254

  watchdog:
    image: mailcow/watchdog:1.10
    build: ${DATA_DIR}/Dockerfiles/watchdog
    volumes:
      - vmail-vol-1:/vmail:ro
    restart: always
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - USE_WATCHDOG=${USE_WATCHDOG:-n}
      - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL:-n}
    # networks:
    #   mailcow-network:
    #     ipv4_address: 172.22.1.248
    #     aliases:
    #       - watchdog

  dockerapi:
    image: mailcow/dockerapi:1.2
    build: ${DATA_DIR}/Dockerfiles/dockerapi
    oom_score_adj: -10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    # networks:
    #   mailcow-network:
    #     aliases:
    #       - dockerapi

  # ipv6nat:
  #   image: robbertkl/ipv6nat
  #   restart: always
  #   privileged: true
  #   network_mode: "host"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /lib/modules:/lib/modules:ro

# networks:
#   mailcow-network:
#     driver: bridge
#     enable_ipv6: true
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.22.1.0/24
#         - subnet: fd4d:6169:6c63:6f77::/64

volumes:
  mysql-vol-1:
    driver: ${STORAGE_DRIVER}
  redis-vol-1:
    driver: ${STORAGE_DRIVER}
  dkim-vol-1:
    driver: ${STORAGE_DRIVER}
  rspamd-vol-1:
    driver: ${STORAGE_DRIVER}
  vmail-vol-1:
    driver: ${STORAGE_DRIVER}
  crypt-vol-1:
    driver: ${STORAGE_DRIVER}
  postfix-vol-1:
    driver: ${STORAGE_DRIVER}