name: Mailcow Rancherized
description: Mailserver suite for rancher
version: 1.2.0
category: Email
maintainer: "Pedro Pereira <pedrogoncalvesp.95@gmail.com>"
projectURL: https://github.com/pedrogoncalvesk/mailcow-rancherized/tree/1.2.0